### ISSUE TITLE
online/offline Status in den Knoten-Clustern visualisieren

### ISSUE THREAD

**Issue by mojoaxel** [ffansbach/de-map#10]
eine Cluster-Visualisierung wie bei [Freifunk Rhein-Neckar](https://www.freifunk-rhein-neckar.de/) wäre toll.

![image](https://cloud.githubusercontent.com/assets/600565/6028244/437b5a94-abe8-11e4-98ba-f4da58bec46e.png)

*P.S. Mir gefallen auch die kleineren dezenteren, weniger verspielten Router-Icon besser.*

**Comment by StilgarBF** [comment]
Die Cluster finde ich großartig, das mit FF-Farben ... ich schaue mir an, wie das umgesetzt wurde.

Die Knoten-Icons kleiner zu machen ist sicher sinnvoll. Speziell der Look von rheinNeckar gefällt mir aber nicht so gut - ich würde gern im Freifunk-Style bleiben. Das das Antennen sind wissen nur Spezialisten - allgemein haben wich für WLAN andere Sysmbole durchgesetzt.

**Comment by StilgarBF** [comment]
https://github.com/SINTEF-9012/PruneCluster

**Comment by mojoaxel** [comment]
:-)
