### ISSUE TITLE
Darmstadt not working

### ISSUE THREAD

**Issue by mweinelt** [ffansbach/de-map#18]
We're using FFAPI 0.4.9 and publish a meshviewer and nodelist technicalType map.

However we are not showing up on the map anymore. Help needed!

https://api.darmstadt.freifunk.net/ffapi.json
bzw.
http://freifunk.linuxlounge.net/ffapi/ffda.json

```
got no data
start parsing
try to find nodeMaps containing any parseable Format
try to find parser for: https://map.darmstadt.freifunk.net/
try to find parser for: https://map.darmstadt.freifunk.net/data/
no parseable nodeMap found
```

**Comment by mweinelt** [comment]
Not it's working again, but I didn't change a thing.

```
try to find nodeMaps containing [nodeList]-Format
parse as [nodeList]
parsing done. 223 nodes found, 194 added, 14 skipped, 0 duplicates, 15 dead
skipping - we already have found a nodeList
```

**Comment by StilgarBF** [comment]
you have added 
        {
            "interval": "60",
            "mapType": "list/status",
            "technicalType": "nodelist",
            "url": "https://map.darmstadt.freifunk.net/data/nodelist.json"
        }
which was not there before.

The parser runs evenry 60minutes around the full hour.

Meshviewer-data is expected to be found under {yourURL}/nodes.json and be marked as "technicalType=ffmap"
If your nodes-file ist under say {yourURL}/data/nodes.json - adding a symlink will help the parse to find the file.

**Comment by mweinelt** [comment]
The base file from which the job updates the ffapi.json every five minutes hasn't been touched since the 6th, so we didn't just insert this today.
```
-rw-r--r--  1 root   root   3.9K Sep  6 20:14 base.json.0.4.9
```

**Comment by mweinelt** [comment]
Also do you want meshviewers `nodes.json` or `nodelist.json`?

**Comment by StilgarBF** [comment]
nodelist ist fine and preferred.

Data from meshviewer/ffmap, netmon, etc is used only if no nodelist is found for a community.

I'll close this issue. Is this ok with you or do you have any open problems regarding the Darmstadt-Community?

**Comment by mweinelt** [comment]
If you are sure there is no issue on your end, be my guest.
