### ISSUE TITLE
Blacklist - why

### ISSUE THREAD

**Issue by JohannesRudolph** [ffansbach/de-map#23]
Is there any particular reason why http://map.freifunk-ruhrgebiet.de/nodes.json is blacklisted? 
Lot's of communities are in the errorCommunities output due to that blacklist.

Could this be documented in the code? 

I found this somewhat related discussion (https://forum.freifunk.net/t/naming-metacommunity/2137/5) but it left me clueless regarding the blacklist anyway.

**Comment by StilgarBF** [comment]
Ich nehme mir die Freiheit auf Deutsch zu antworten - weil langer Arbeitstag und ich bin etwas müde :-)

Es gibt hier einen Thread: https://forum.freifunk.net/t/sonderlocke-fuer-ruhrgebiet-in-freifunk-karte-implementiert/8375

Also Ruhrgebiet: Die haben eine neue Karte und trennen soweit ich es verstanden habe ihr Untergruppen nach und nach technisch mehr ab.
Ziel ist wohl, dass die Untergruppen auch in ihre Community-Files ihre eigenen Karten eintragen.

Das wiederum - wenn es denn passieren würde - könnte auch dafür sorgen, dass die Knoten der einzelnen Gruppen auch entsprechend zugeordnet werden. - Und nicht der ersten Community zugesprochen werden, die zufällig die Karte mit den Knoten aller Subcommunities liefert.

Ich bin mit allen Blacklist und handverdrahteten Extra-Communities unglücklich.
Im Idealfall würde alles über die API laufen, aber leider kommt es manchmal zu dopplungen oder Datensatzfehler.

hilft das weiter?
