### ISSUE TITLE
Crawler should output data in nodelist format

### ISSUE THREAD

**Issue by JohannesRudolph** [ffansbach/de-map#24]
It would be convenient (and more consistent) if we used the nodelist format between the js map-client and the server as well. Stops the proliferation of formats....

Since most fields in nodelist are optional, I see no problems from doing so (the client would even now how fresh the data is).

**Comment by StilgarBF** [comment]
I need details here.
What do you mean by "js map-client" and "server"
Do you mean specifically the freifunk-karte.de?

I made the json thats used by leaflet as small as possible to limit bandwidth usage (yes I could further shorten the keys - but that would make it unreadable).
As long as I have not solved the problem of sending smaller data-packages depending on zoom and viewed region, I do not want to add more structure to that format.

**Comment by christian-weiss** [comment]
I guess "js map-client" is just an other name for "frontend" and "server" means all the PHP stuff (crawler, DB, cache, crons, etc.) for freifunk-karte.de and other instances of this github repo.

Your current format makes sense for its purpose (be small, reduce bandwidth), but there is still some potential to reduce its footprint even further.

There is no need for a NodeList-formated export as long as no one asks to provide the full node list for download (to consume it with other apps).

Lets close this ticket.
