### ISSUE TITLE
communities using firmware of Berlin listed as community Berlin

### ISSUE THREAD

**Issue by ffcb** [ffansbach/de-map#26]
hi,

for example our community is listed as community Berlin. we use the firmware "kathleen" of the community Berlin only with our own settings. other communities which are using "kathleen" are listed as Berlin too, see Potsdam or Eberswalde.

**Comment by StilgarBF** [comment]
Ich antworte auf Deutsch, weil ich annehme, dass wir die selbe Sprache sprechen.

Die Freifunk-Karte kann nicht hellsehen. ;-)
Um dieses Manko auszugleichen werden alle Communities aus der Freifunk-Community-Api ausgelesen.
Dann werden deren API-Files gelesen und aus denen die Map-Einträge.
Von der URL, die dort hinterlegt ist wird dann versucht etwas Brauchbares zu beziehen, wo Knotendaten ausgelesen werden können

Cottbus liefert folgendes Communityfile:
https://freifunk-cottbus.de/FreifunkCottbus-api.json
darin ist die openwifi-Map verzeichnet.

Alle Knoten der openwifimap werden eingelesen und aufgenommen.
Da Berlin diese auch (ursprünglich als Erste afaik) verwendet und auch noch alphabetisch vor Cottbus steht, werden die Knoten der openwifimap Berlin zugeordnet.
Werden dann weitere Communities mit der selben Karte gefunden werden nur noch Duplikate erkannt - und natürlich nicht angezeigt.

Ausweg für euch:
Liefert etwas, was NUR eure Knote enthält.
Das sollte dann das nodelist-format sein. Communities, die Nodelist liefern werden bevorzugt.
Der parser findet dann eure Nodelist mit NUR euren Knoten und übernimmt diese für die Karte.
Wenn dann die openwifimap eingelesen wird werden die bereits für euch eingelesenen Knoten ignoriert.

nodelist format:
https://github.com/ffansbach/nodelist

Beispiel-Nodelist:
https://netmon.freifunk-emskirchen.de/api/router_json.php

Beispiel für Nodelist-Eintrag in API-File:
https://netmon.freifunk-emskirchen.de/api/community.php

hilft das weiter?

**Comment by StilgarBF** [comment]
no response
