### ISSUE TITLE
Reduce footprint of "de-map-nodelist"-format

### ISSUE THREAD

**Issue by christian-weiss** [ffansbach/de-map#31]
Inspired by #24 i file this issue.

Your current format (nodelist for frontend) makes sense for its purpose (be small, reduce bandwidth), but there is still some potential to reduce its footprint even further.

Data file: uncompressed it is currently 6,30 MB, gziped 1,35 MB. Could be a bit "heavy" on mobiles with bad internet connection. 

Load times (with simulated bandwidth throttling in firefox; 92 requests, all files gziped total 4.15 MB):
LTE: 11.13 seconds
3G: 16.73 seconds
2G: 1.28 minutes
GPRS: 11.36 minutes

By reducing the keys to just one letter we could **reduce** the uncompressed file from 6.3 MB to 5.1 MB => **approx 19%**, which is significant!
```
sed -i 's/"communities"/"c"/g' nodes_reduced.json
sed -i 's/"name"/"n"/g' nodes_reduced.json
sed -i 's/"url"/"u"/g' nodes_reduced.json
sed -i 's/"status"/"s"/g' nodes_reduced.json
sed -i 's/"long"/"g"/g' nodes_reduced.json
sed -i 's/"lat"/"t"/g' nodes_reduced.json
sed -i 's/"clients"/"l"/g' nodes_reduced.json
sed -i 's/"community"/"y"/g' nodes_reduced.json
sed -i 's/"id"/"i"/g' nodes_reduced.json
```
This could also reduce JavaScript time to parse it.

**Comment by christian-weiss** [comment]
found another key "meta" which could be reduced to "m".
We could also reduce the precision of long and lat, as 5 decimal places (precision is 1.11 meter) should be enough for our use case. Dropping trailing zeros could also tweak it a bit.

For "communities" we may not need a "name" as a community-key (as we have a "name" field for the community name), an index number could be enough for this key.

**Comment by StilgarBF** [comment]
won't consider for now
gzip is not great, but good enough at compressing strings than are in the file multiple times.
An uncompressed reduction of 20% (following your suggestions) resulted in less than 3% reduced size compressed.

A bigger impact could be achieved by pre-calculating clusters on the server,
sending out a cluster file first on wide zoom and viewport specific node lists when zooming in.
