### ISSUE TITLE
freifunk-karte.de statistics not updating anymore?

### ISSUE THREAD

**Issue by T-X** [ffansbach/de-map#37]
Screenshot: 14th July 2022

![freifunk-karte de-stale](https://user-images.githubusercontent.com/350145/178975981-ff642471-6d0f-41fd-a75d-caccf854d85c.png)

It seems like the statistics on freifunk-karte.de last updated 2nd of January 2022 and 7th of June 2022. Is the updating process stale, did something break?

**Comment by mojoaxel** [comment]
@StilgarBF I'm willing to look into this if you give me access to the server.

**Comment by StilgarBF** [comment]
I am back. sorry for the inactivity. I had to focus my energy away from FF for a longer time.
The parser process on a local server was running in a timeout and I did not notice for a year. So no new map files had not been uploaded to the map.

was a small fix.

Still I would be willing to accept any help to make the setup more reliable and potentially also rewrite the parser.

will post a call for help here soon.

thank you @mojoaxel for the ping. that woke me up

**Comment by xnumad** [comment]
To ensure users will quickly notice outdated data if it ever happens again, making the website show a fat warning dialog about outdated data would be useful 😆

Or simply this value somewhere on the map page.
https://www.freifunk-karte.de/debug.php:
> Letzter Parserlauf: 2022-06-07T07:15:52+02:00

I looked into the code for an hour before finding out.
