### ISSUE TITLE
Heatmaps Zoom is broken

### ISSUE THREAD

**Issue by Djfe** [ffansbach/de-map#38]
If I select one of the two heat maps, then they load once.
They don't refresh resolution/scale on zooming. at the moment

The shape of germany when zoomed in.
![Heatmap nodes Edge](https://github.com/ffansbach/de-map/assets/5685512/3066a789-3ec2-4f64-8191-ca7c1d02c964)
The shape of Germany when zoomed out.
![Heatmap users Firefox](https://github.com/ffansbach/de-map/assets/5685512/2da4314d-b61f-4146-8a28-a111bd4d15da)

The current workaround is to reselect the checkbox.

Affected are Firefox (tested Nightly), Edge and Chrome (tested Releases of those)

**Comment by StilgarBF** [comment]
fixed with "newer" version of the heatmap plugin. - which seems to be abandoned now
