### ISSUE TITLE
Falcher Link zu FF Rheinland

### ISSUE THREAD

**Issue by clonejo** [ffansbach/de-map#9]
Der Community-Link (offenbar aller) Router des Freifunk Rheinland zeigt auf die [Wikiseite der Community Kempen](https://wiki.freifunk-rheinland.net/Kempen).

Etwa dieser Router in Neuss: ![Screenshot der Karte](http://clnj.de/~clonejo/ffkarte-link.png)

Sinnvoller wäre ein Link auf den [Freifunk Rheinland](https://freifunk-rheinland.net/) selbst, oder auf dessen [Wiki](https://wiki.freifunk-rheinland.net/Hauptseite).
Idealerweise würde jeweils die passende Community verlinkt, aber dafür bräuchte es eine getrennte Routerliste pro Community.

**Comment by StilgarBF** [comment]
Hi,

Problem hier ist, dass ich aus den Community-Files zwar ablesen kann, welche Community zu welcher Metacommunity gehört, nicht aber, was die bevorzugte Webseite der Metacommunity ist.

Api-files für Metacommunities haben wir nicht.

Ich lasse mir was einfallen - muss dann halt ein Mapping fest verdrahten.

**Comment by kokel** [comment]
Hi,

das gleiche Problem haben wir mit Mainz Wiesbaden auch (Meta-Community Freifunk MWU).
In den Api-Files haben wir jeweils unsere Homepage hinterlegt. Warum nicht einfach diese URL nehmen? Würde uns zumindest schon reichen......

**Comment by StilgarBF** [comment]
@kokel @clonejo ist euch mit den letzten Änderungen geholfen?

Es wird jetzt immer community und metacommunity angezeigt. der Link geht immer auf die community-Seite, die im Apifile stand, aus dem auch die Nodes kamen.

**Comment by kokel** [comment]
@StilgarBF Jetzt stimmt es, vielen Dank!
